#!/usr/bin/env bash

docker_tag=ectoplasm/plantuml:latest

if [[ $# -ne 1 ]]; then
  echo "No src diagram specified. Quitting."
  exit 1
else
  srcfile=$1
fi

docker run --rm -v $(pwd):/opt/plantuml/src/ $docker_tag $srcfile
